---
name: "错误报告"
description: "报告集成中的错误"
labels: "Bug"
body:
- type: markdown
  attributes:
    value: 在提交新问题之前，请先搜索现有问题，看看是否有其他人遇到了相同的问题。
- type: textarea
  attributes:
    label: "系统健康详情"
    description: "从 Home Assistant 的系统健康卡片中粘贴数据 (https://www.home-assistant.io/more-info/system-health#github-issues)"
  validations:
    required: true
- type: checkboxes
  attributes:
    label: 清单
    options:
      - label: 我已为我的安装启用了调试日志。
        required: true
      - label: 我已经尽我所能填写了问题模板。
        required: true
      - label: 该问题仅包含 1 个问题（如果您有多个问题，请为每个问题单独提交）。
        required: true
      - label: 该问题不是任何[之前问题](https://github.com/XiaoMiku01/hass-hjq/issues?q=is%3Aissue+label%3A%22Bug%22+)的重复问题。
        required: true
- type: textarea
  attributes:
    label: "描述问题"
    description: "对问题的清晰简明描述。"
  validations:
    required: true
- type: textarea
  attributes:
    label: 复现步骤
    description: "没有复现步骤，将很难修复。填写此部分非常重要。没有此内容的问题将被关闭。"
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: "调试日志"
    description: "要启用调试日志，请查看此链接 (https://www.home-assistant.io/integrations/logger/) ，这**需要**包含从 Home Assistant 启动到遇到问题的所有内容。"
    render: text
  validations:
    required: true

- type: textarea
  attributes:
    label: "诊断转储"
    description: "拖动诊断转储文件到这里。(详情请见 https://www.home-assistant.io/integrations/diagnostics/)"
